# Generated by Django 3.1.6 on 2021-03-26 03:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210323_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
