# Generated by Django 3.1.6 on 2021-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0006_historyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryRecord',
        ),
    ]
